window.__LAW_APP_TEST_DATA = {
  "version": "1.0.0",
  "timestamp": "2026-01-08T09:10:00.000Z",
  "data": {
    "clients": [
      {
        "id": 1,
        "name": "أحمد علي عبد المقصود",
        "address": "15 شارع التحرير، طنطا، الغربية",
        "phone": "01010001001"
      },
      {
        "id": 2,
        "name": "منة الله محمد السيد",
        "address": "8 شارع الاستاد، كفر الشيخ",
        "phone": "01120002002"
      },
      {
        "id": 3,
        "name": "محمود السيد عبد الله",
        "address": "الحي العاشر، العاشر من رمضان، الشرقية",
        "phone": "01030003003"
      },
      {
        "id": 4,
        "name": "سارة محمود عادل",
        "address": "22 شارع الجامعة، المنصورة",
        "phone": "01240004004"
      },
      {
        "id": 5,
        "name": "محمد فوزي إبراهيم",
        "address": "1 شارع الجيش، الإسماعيلية",
        "phone": "01050005005"
      },
      {
        "id": 6,
        "name": "ياسمين حسن عبد الرحمن",
        "address": "9 شارع البحر، بورسعيد",
        "phone": "01060006006"
      }
    ],
    "opponents": [
      {
        "id": 1,
        "name": "شركة الأفق للاستثمار العقاري",
        "address": "برج النيل، المعادي، القاهرة",
        "phone": "0225559001"
      },
      {
        "id": 2,
        "name": "سعيد محمود العطار",
        "address": "45 شارع الهرم، الجيزة",
        "phone": "01155998822"
      },
      {
        "id": 3,
        "name": "بنك القاهرة - فرع بورسعيد",
        "address": "شارع الجمهورية، بورسعيد",
        "phone": "0663456789"
      },
      {
        "id": 4,
        "name": "شركة النجم للشحن والنقل",
        "address": "78 شارع الصناعة، مدينة السادات",
        "phone": "0155776699"
      },
      {
        "id": 5,
        "name": "مروة عبد العزيز فرج",
        "address": "33 شارع الأزهر، الفيوم",
        "phone": "01244887766"
      },
      {
        "id": 6,
        "name": "شركة الحماية للتأمين",
        "address": "المهندسين، الجيزة",
        "phone": "0233556677"
      }
    ],
    "cases": [
      {
        "id": 1,
        "clientId": 1,
        "opponentId": 1,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "2156",
        "caseYear": "2025",
        "court": "محكمة طنطا الابتدائية",
        "circuitNumber": "3 مدني",
        "caseType": "مدني",
        "subject": "إخلاء شقة مؤجرة",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2025-001",
        "appealNumber": "118",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-001",
        "isArchived": false,
        "notes": "مطالبة بالإخلاء لعدم سداد الإيجار"
      },
      {
        "id": 2,
        "clientId": 1,
        "opponentId": 2,
        "clientCapacity": "مستأنف",
        "opponentCapacity": "مستأنف ضده",
        "caseNumber": "7781",
        "caseYear": "2025",
        "court": "محكمة طنطا الابتدائية",
        "circuitNumber": "7 مدني",
        "caseType": "مدني",
        "subject": "مطالبة مالية",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2025-002",
        "appealNumber": "245",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-002",
        "isArchived": false,
        "notes": "مطالبة بمبلغ مستحق نظير عقد خدمات"
      },
      {
        "id": 3,
        "clientId": 1,
        "opponentId": 3,
        "clientCapacity": "شاكي",
        "opponentCapacity": "مشكو في حقه",
        "caseNumber": "450",
        "caseYear": "2024",
        "court": "محكمة جنح بورسعيد",
        "circuitNumber": "3 جنح",
        "caseType": "جنح",
        "subject": "محضر تبديد منقولات",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2024-003",
        "appealNumber": "67",
        "appealYear": "2026",
        "cassationNumber": "13",
        "cassationYear": "2026",
        "fileNumber": "FILE-003",
        "isArchived": false,
        "notes": "طلب رفع الحجز على حساب بنكي"
      },

      {
        "id": 4,
        "clientId": 2,
        "opponentId": 4,
        "clientCapacity": "مستأنف",
        "opponentCapacity": "مستأنف ضده",
        "caseNumber": "3421",
        "caseYear": "2025",
        "court": "محكمة كفر الشيخ الابتدائية",
        "circuitNumber": "1 مدني",
        "caseType": "مدني",
        "subject": "استئناف حكم تعويض",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2025-004",
        "appealNumber": "311",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-004",
        "isArchived": false,
        "notes": "استئناف حكم تعويض صادر ضد الموكل"
      },
      {
        "id": 5,
        "clientId": 2,
        "opponentId": 4,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "9921",
        "caseYear": "2025",
        "court": "محكمة كفر الشيخ الابتدائية",
        "circuitNumber": "4 تجاري",
        "caseType": "تجاري",
        "subject": "مطالبة بقيمة شحن",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2025-005",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-005",
        "isArchived": false,
        "notes": "مطالبة بقيمة شحن متأخر لنفس الخصم"
      },

      {
        "id": 6,
        "clientId": 3,
        "opponentId": 5,
        "clientCapacity": "متهم",
        "opponentCapacity": "مجني عليه",
        "caseNumber": "6060",
        "caseYear": "2023",
        "court": "محكمة جنح العاشر من رمضان",
        "circuitNumber": "2 جنح",
        "caseType": "جنائي",
        "subject": "جنحة إيصال أمانة",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2023-006",
        "appealNumber": "90",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-006",
        "isArchived": false,
        "notes": "نزاع على توريد بضاعة وطلبات تعويض"
      },

      {
        "id": 7,
        "clientId": 4,
        "opponentId": 6,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "1188",
        "caseYear": "2025",
        "court": "محكمة المنصورة الابتدائية",
        "circuitNumber": "2 مدني",
        "caseType": "مدني",
        "subject": "تعويض حادث",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2025-007",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-007",
        "isArchived": false,
        "notes": "مطالبة تأمين وتعويض عن حادث"
      },
      {
        "id": 8,
        "clientId": 5,
        "opponentId": 2,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "220",
        "caseYear": "2024",
        "court": "محكمة الإسماعيلية الابتدائية",
        "circuitNumber": "9 مدني",
        "caseType": "مدني",
        "subject": "إثبات ملكية",
        "caseStatus": "جاري النظر",
        "poaNumber": "POA-2024-008",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "FILE-008",
        "isArchived": false,
        "notes": "دعوى إثبات ملكية على عقار"
      },
      {
        "id": 9,
        "clientId": 6,
        "opponentId": 1,
        "clientCapacity": "مستأنف",
        "opponentCapacity": "مستأنف ضده",
        "caseNumber": "77",
        "caseYear": "2022",
        "court": "محكمة بورسعيد الابتدائية",
        "circuitNumber": "1 مدني",
        "caseType": "مدني",
        "subject": "فسخ عقد إيجار",
        "caseStatus": "منتهية",
        "poaNumber": "POA-2022-009",
        "appealNumber": "55",
        "appealYear": "2023",
        "cassationNumber": "19",
        "cassationYear": "2024",
        "fileNumber": "FILE-009",
        "isArchived": true,
        "notes": "قضية منتهية للأرشفة"
      }
    ],
    "sessions": [
      {
        "id": 1,
        "clientId": 1,
        "caseId": 1,
        "sessionDate": "2026-01-06",
        "sessionTime": "10:00",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مرافعة",
        "roll": "12",
        "inventoryNumber": "101",
        "inventoryYear": "2025",
        "decision": "تأجيل لإعلان الخصم",
        "requests": "إثبات إعلان",
        "notes": "أول جلسة"
      },
      {
        "id": 2,
        "clientId": 1,
        "caseId": 1,
        "sessionDate": "2026-01-09",
        "sessionTime": "11:30",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مستندات",
        "roll": "12",
        "inventoryNumber": "101",
        "inventoryYear": "2025",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم عقد الإيجار",
        "notes": "تقديم مستندات"
      },

      {
        "id": 3,
        "clientId": 1,
        "caseId": 2,
        "sessionDate": "2026-01-03",
        "sessionTime": "09:30",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مرافعة",
        "roll": "6",
        "inventoryNumber": "202",
        "inventoryYear": "2025",
        "decision": "تأجيل للمرافعة",
        "requests": "طلب إلزام بالسداد",
        "notes": "جلسة مرافعة"
      },
      {
        "id": 4,
        "clientId": 1,
        "caseId": 2,
        "sessionDate": "2026-01-13",
        "sessionTime": "10:30",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مستندات",
        "roll": "6",
        "inventoryNumber": "202",
        "inventoryYear": "2025",
        "decision": "ضم إيصال سداد جزئي",
        "requests": "ضم إيصال",
        "notes": "مستندات"
      },
      {
        "id": 5,
        "clientId": 1,
        "caseId": 2,
        "sessionDate": "2026-01-20",
        "sessionTime": "12:00",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "حكم",
        "roll": "6",
        "inventoryNumber": "202",
        "inventoryYear": "2025",
        "decision": "حجز للحكم",
        "requests": "مرافعة ختامية",
        "notes": "قبل النطق بالحكم"
      },

      {
        "id": 6,
        "clientId": 1,
        "caseId": 3,
        "sessionDate": "2026-01-05",
        "sessionTime": "13:00",
        "court": "محكمة بورسعيد الابتدائية",
        "sessionType": "طلب",
        "roll": "18",
        "inventoryNumber": "33",
        "inventoryYear": "2026",
        "decision": "تأجيل لتقديم إفادة البنك",
        "requests": "ضم إفادة",
        "notes": "جلسة واحدة مبدئية"
      },

      {
        "id": 7,
        "clientId": 2,
        "caseId": 4,
        "sessionDate": "2026-01-07",
        "sessionTime": "10:00",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مرافعة",
        "roll": "8",
        "inventoryNumber": "77",
        "inventoryYear": "2025",
        "decision": "تأجيل لإعلان",
        "requests": "إعلان صحيح",
        "notes": "جلسة أولى"
      },
      {
        "id": 8,
        "clientId": 2,
        "caseId": 4,
        "sessionDate": "2026-01-21",
        "sessionTime": "11:00",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مستندات",
        "roll": "8",
        "inventoryNumber": "77",
        "inventoryYear": "2025",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم تقرير",
        "notes": "مستندات"
      },

      {
        "id": 9,
        "clientId": 2,
        "caseId": 5,
        "sessionDate": "2026-01-08",
        "sessionTime": "09:45",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مرافعة",
        "roll": "14",
        "inventoryNumber": "88",
        "inventoryYear": "2025",
        "decision": "تأجيل للمرافعة",
        "requests": "تقديم فواتير",
        "notes": "نفس الخصم - قضية مختلفة"
      },
      {
        "id": 10,
        "clientId": 2,
        "caseId": 5,
        "sessionDate": "2026-01-23",
        "sessionTime": "12:15",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مستندات",
        "roll": "14",
        "inventoryNumber": "88",
        "inventoryYear": "2025",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم سند شحن",
        "notes": "متابعة"
      },

      {
        "id": 11,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-02",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل للإعلان",
        "requests": "إعلان",
        "notes": "1 من 11"
      },
      {
        "id": 12,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-04",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مستندات",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "ضم مستندات وتأجيل",
        "requests": "ضم فواتير",
        "notes": "2 من 11"
      },
      {
        "id": 13,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-06",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "خبرة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تعيين خبير",
        "requests": "طلب خبرة",
        "notes": "3 من 11"
      },
      {
        "id": 14,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-08",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مناقشة تقرير",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل للمرافعة",
        "requests": "ملاحظات على التقرير",
        "notes": "4 من 11"
      },
      {
        "id": 15,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-11",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "مرافعة",
        "notes": "5 من 11"
      },
      {
        "id": 16,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-13",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مستندات",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "ضم مستندات",
        "requests": "ضم مراسلات",
        "notes": "6 من 11"
      },
      {
        "id": 17,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-15",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "حجز للحكم",
        "requests": "طلبات ختامية",
        "notes": "7 من 11"
      },
      {
        "id": 18,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-17",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "حكم",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "إعادة فتح باب المرافعة",
        "requests": "",
        "notes": "8 من 11"
      },
      {
        "id": 19,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-19",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "مرافعة إضافية",
        "notes": "9 من 11"
      },
      {
        "id": 20,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-22",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "حجز للحكم",
        "requests": "",
        "notes": "10 من 11"
      },
      {
        "id": 21,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-01-26",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "حكم",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "الحكم للموكل",
        "requests": "استخراج صيغة تنفيذية",
        "notes": "11 من 11"
      },

      {
        "id": 22,
        "clientId": 4,
        "caseId": 7,
        "sessionDate": "2026-01-14",
        "sessionTime": "09:30",
        "court": "محكمة المنصورة الابتدائية",
        "sessionType": "مرافعة",
        "roll": "25",
        "inventoryNumber": "301",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "ضم تقرير",
        "notes": ""
      },
      {
        "id": 23,
        "clientId": 5,
        "caseId": 8,
        "sessionDate": "2026-01-16",
        "sessionTime": "11:00",
        "court": "محكمة الإسماعيلية الابتدائية",
        "sessionType": "مرافعة",
        "roll": "7",
        "inventoryNumber": "401",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "",
        "notes": ""
      }
    ],
    "administrative": [
      {
        "id": 1,
        "clientId": 1,
        "task": "تحضير ملف القضية وتجميع المستندات",
        "dueDate": "2026-01-09",
        "completed": false,
        "location": "مكتب المحاماة",
        "notes": "مطلوب تجهيز ملف القضية قبل جلسة الغد",
        "assignedTo": "السكرتارية"
      },
      {
        "id": 2,
        "clientId": 2,
        "task": "متابعة إعلان الخصم (شركة النجم للشحن)",
        "dueDate": "2026-01-10",
        "completed": false,
        "location": "قلم المحضرين",
        "notes": "التأكد من تمام الإعلان وتسليم الإيصال",
        "assignedTo": "المحامي"
      },
      {
        "id": 3,
        "clientId": 3,
        "task": "متابعة تقرير الخبرة ومراجعة الملاحظات",
        "dueDate": "2026-01-12",
        "completed": false,
        "location": "مكتب الخبير",
        "notes": "استلام نسخة من التقرير ومراجعة البنود",
        "assignedTo": "المحامي"
      },
      {
        "id": 4,
        "clientId": 4,
        "task": "مراجعة مطالبة التأمين وتجهيز مذكرة",
        "dueDate": "2026-01-15",
        "completed": false,
        "location": "مكتب المحاماة",
        "notes": "تجهيز مذكرة مختصرة وطلب ضم مستندات",
        "assignedTo": "المحامي"
      },
      {
        "id": 5,
        "clientId": null,
        "task": "جرد المواعيد وإرسال تذكير بالجلسات",
        "dueDate": "2026-01-08",
        "completed": true,
        "location": "مكتب المحاماة",
        "notes": "تم إرسال التذكيرات",
        "assignedTo": "السكرتارية"
      }
    ],
    "accounts": [
      {
        "id": 1,
        "clientId": 1,
        "caseId": 1,
        "paymentDate": "2026-01-06",
        "totalFees": 15000,
        "paidFees": 5000,
        "expenses": 650,
        "remaining": 9350,
        "notes": "دفعة مقدمة + مصروفات إعلان",
        "createdAt": "2026-01-06T09:15:00.000Z",
        "updatedAt": "2026-01-06T09:15:00.000Z"
      },
      {
        "id": 2,
        "clientId": 1,
        "caseId": 2,
        "paymentDate": "2026-01-09",
        "totalFees": 22000,
        "paidFees": 12000,
        "expenses": 1100,
        "remaining": 8900,
        "notes": "سداد جزء من الأتعاب + مصروفات جلسة",
        "createdAt": "2026-01-09T12:30:00.000Z",
        "updatedAt": "2026-01-09T12:30:00.000Z"
      },
      {
        "id": 3,
        "clientId": 2,
        "caseId": 4,
        "paymentDate": "2026-01-07",
        "totalFees": 18000,
        "paidFees": 6000,
        "expenses": 900,
        "remaining": 11100,
        "notes": "تم سداد دفعة أولى",
        "createdAt": "2026-01-07T08:40:00.000Z",
        "updatedAt": "2026-01-07T08:40:00.000Z"
      },
      {
        "id": 4,
        "clientId": 3,
        "caseId": 6,
        "paymentDate": "2026-01-08",
        "totalFees": 30000,
        "paidFees": 15000,
        "expenses": 2500,
        "remaining": 12500,
        "notes": "تجهيز ملف خبرة + انتقالات",
        "createdAt": "2026-01-08T10:00:00.000Z",
        "updatedAt": "2026-01-08T10:00:00.000Z"
      },
      {
        "id": 5,
        "clientId": 4,
        "caseId": 7,
        "paymentDate": "2026-01-14",
        "totalFees": 16000,
        "paidFees": 4000,
        "expenses": 500,
        "remaining": 11500,
        "notes": "دفعة مقدمة",
        "createdAt": "2026-01-14T09:45:00.000Z",
        "updatedAt": "2026-01-14T09:45:00.000Z"
      },
      {
        "id": 6,
        "clientId": 5,
        "caseId": 8,
        "paymentDate": "2026-01-16",
        "totalFees": 14000,
        "paidFees": 7000,
        "expenses": 300,
        "remaining": 6700,
        "notes": "تم سداد نصف الأتعاب",
        "createdAt": "2026-01-16T11:20:00.000Z",
        "updatedAt": "2026-01-16T11:20:00.000Z"
      },
      {
        "id": 7,
        "clientId": 6,
        "caseId": 9,
        "paymentDate": "2026-01-05",
        "totalFees": 12000,
        "paidFees": 12000,
        "expenses": 0,
        "remaining": 0,
        "notes": "قضية منتهية/أتعاب مسددة",
        "createdAt": "2026-01-05T13:10:00.000Z",
        "updatedAt": "2026-01-05T13:10:00.000Z"
      }
    ],
    "expertSessions": [
      {
        "id": 1,
        "clientId": 3,
        "caseNumber": "6060/2023",
        "sessionType": "معاينة",
        "status": "مجدولة",
        "sessionDate": "2026-01-10",
        "sessionTime": "12:00",
        "expertName": "م/ أحمد حسني",
        "notes": "معاينة موقع النزاع وإعداد محضر" 
      },
      {
        "id": 2,
        "clientId": 3,
        "caseNumber": "6060/2023",
        "sessionType": "تقديم مستندات",
        "status": "تمت",
        "sessionDate": "2026-01-06",
        "sessionTime": "11:00",
        "expertName": "م/ أحمد حسني",
        "notes": "تم تسليم صور المستندات للخبير" 
      },
      {
        "id": 3,
        "clientId": 1,
        "caseNumber": "2156/2025",
        "sessionType": "مناقشة",
        "status": "مجدولة",
        "sessionDate": "2026-01-18",
        "sessionTime": "10:30",
        "expertName": "د/ محمد عبد السلام",
        "notes": "مناقشة نقاط النزاع أمام الخبير" 
      },
      {
        "id": 4,
        "clientId": 2,
        "caseNumber": "3421/2025",
        "sessionType": "تقرير خبير",
        "status": "تمت",
        "sessionDate": "2026-01-07",
        "sessionTime": "14:00",
        "expertName": "د/ نهى السيد",
        "notes": "استلام نسخة من تقرير الخبرة" 
      },
      {
        "id": 5,
        "clientId": 4,
        "caseNumber": "1188/2025",
        "sessionType": "أخرى",
        "status": "ملغية",
        "sessionDate": "2026-01-13",
        "sessionTime": "09:00",
        "expertName": "م/ خالد طه",
        "notes": "تم الإلغاء لعدم حضور الخصم" 
      }
    ],
    "clerkPapers": [
      {
        "id": 1,
        "clientId": 1,
        "paperType": "إعلان",
        "paperNumber": "2156/2025",
        "clerkOffice": "قلم محضري طنطا",
        "deliveryDate": "2026-01-06",
        "receiptDate": "2026-01-08",
        "notes": "تم تسليم الإعلان للخصم"
      },
      {
        "id": 2,
        "clientId": 2,
        "paperType": "إنذار",
        "paperNumber": "3421/2025",
        "clerkOffice": "قلم محضري كفر الشيخ",
        "deliveryDate": "2026-01-07",
        "receiptDate": "2026-01-10",
        "notes": "إنذار على يد محضر بخصوص المديونية"
      },
      {
        "id": 3,
        "clientId": 3,
        "paperType": "إعلان",
        "paperNumber": "6060/2023",
        "clerkOffice": "قلم محضري العاشر من رمضان",
        "deliveryDate": "2026-01-04",
        "receiptDate": "2026-01-06",
        "notes": "إعلان موعد الخبرة"
      },
      {
        "id": 4,
        "clientId": 4,
        "paperType": "أخرى",
        "paperNumber": "1188/2025",
        "clerkOffice": "قلم محضري المنصورة",
        "deliveryDate": "2026-01-12",
        "receiptDate": "",
        "notes": "جارٍ متابعة الاستلام"
      },
      {
        "id": 5,
        "clientId": 5,
        "paperType": "إنذار",
        "paperNumber": "220/2024",
        "clerkOffice": "قلم محضري الإسماعيلية",
        "deliveryDate": "2026-01-15",
        "receiptDate": "2026-01-17",
        "notes": "تم الإنذار وتم استلام أصل الورقة"
      }
    ]
  }
};
